### PR TITLE
Fix boolean closure values when deserializing functions

### LINKED ISSUE #27: Incorrect boolean deserialization in function closures
Boolean values which are closed over in a function which is in turn passed to a sparkplug function (like `spark/map`), are incorrectly deserialized. The `false` return type does not appear to be equivalent to `Boolean/FALSE`, but rather it appears to be a new Boolean via `(Boolean. false)`. This incorrect deserialization then leads to invalid results for typical Clojure idioms, like `(if flag _ _)`. See https://clojure.org/reference/special_forms#if.

A small test which demonstrates the incorrect behavior:
```
(deftest boolean-boxing
  (testing "boolean values are boxed correctly when closed over and used with spark function"
    (let [test-flag false]
      (is (= [0 1 2]
             (->> (rdd/parallelize *sc* [1 2 3])
                  (spark/map (fn [x] 
                               (if test-flag 
                                 (inc x)
                                 (dec x))))
                  (spark/into [])))))))
```
In this case, the serialized/deserialized `test-flag` -- although starting with a `false` value -- evaluates to truthy in the `if` form.

### PR DESCRIPTION
**Pull request by greglook**
A couple of intersecting issues cause incorrect behavior when a function which closes over a boolean value is serialized to execute on a Spark worker. We're relying on Java's default object serialization for the most part, since functions are custom classes with unique fields based on the code inside them. The closure values are represented as instance fields of type `Object`, so booleans get boxed into a `Boolean` value.

Booleans in Java have two canonical instances for the true and false boxed values, `Boolean/TRUE` and `Boolean/FALSE`, respectively; in Clojure, a "truthiness" evaluation only considers `nil` and `Boolean/FALSE` to be falsey values. Unfortunately, the language implementation of `java.lang.Boolean` doesn't customize the behavior of the `Serializable` interface, so when we deserialize the closed-over value we get back a _new_ `(Boolean. false)` instance, which Clojure treats as truthy. Thus the bug.

To fix this, we can do something _extremely gross_ but workable, which is to walk the deserialized function and update any closed-over `Boolean` values to map them back to the two canonical instances.

Fixes #27

### CODE REVIEW

File: sparkplug-core/src/java/sparkplug/function/SerializableFn.java [hunk 1]
```diff
@@ -60,6 +64,72 @@ protected SerializableFn(IFn fn, Collection<String> namespaces) {
...
+        try {
+            if (!field.isAccessible()) {
+                field.setAccessible(true);
+            }
+            return field.get(obj);
+        } catch (Exception ex) {
+            logger.trace("Failed to access field " + field.toString() + ": " + ex.getClass().getName());
+            return null;
+        }
+    }
```
Comment (steve-ashton-amp) [inline sparkplug-core/src/java/sparkplug/function/SerializableFn.java:85]: Does the Java version of `accessField` behave differently than the prior Clojure version?

**Review by steve-ashton-amp — COMMENTED** [review]
I've built this locally and tested it against the code which gave me the problem reported here https://github.com/amperity/sparkplug/issues/27.
That code now functions as expected with properly deserialized booleans.
👍

File: sparkplug-core/src/java/sparkplug/function/SerializableFn.java (hunk 1 above)
Comment (greglook) [reply sparkplug-core/src/java/sparkplug/function/SerializableFn.java:85]: The logic is identical, except that the Java version uses the SLF4J logging interface, and the Clojure version was using `clojure.tools.logging` (which ultimately forwarded to the SLF4J backend).

File: sparkplug-core/src/java/sparkplug/function/SerializableFn.java [hunk 2]
```diff
@@ -60,6 +64,72 @@ protected SerializableFn(IFn fn, Collection<String> namespaces) {
...
+            return;
+        }
+
+        // For collection-like objects, just traverse their elements.
+        if (obj instanceof Iterable) {
+            for (Object el : (Iterable)obj) {
+                fixBooleans(el);
+            }
+            return;
+        }
```
Comment (scgerkin) [inline sparkplug-core/src/java/sparkplug/function/SerializableFn.java]: any concerns with a stack overflow? I could see the stack getting very large for deeply nested structures.

Comment (greglook) [reply sparkplug-core/src/java/sparkplug/function/SerializableFn.java]: Not especially; on default JVM settings we should be able to get to a depth of around 20k frames before an overflow, depending on how much each stack frame is allocating - here we're only preserving a handful of `Object` references in each call. We also already do this same walk logic on the serializing side to discover namespace references in the function, so if there _were_ a closed-over object that was too nested, we probably would have failed to transmit it from the driver in the first place.

I'm realizing we probably _do_ want a visited set here too though, in case a function closes over a self-referential object somehow. 🤔 That's pretty rare in Clojure, but not impossible if there are Java classes in play.

**Review by scgerkin — APPROVED** [review]
Makes sense to me
